name: build

on:
  workflow_dispatch:
  push:
    tags:
      - dev
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - platform: windows-latest
          - platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install save_point cli
        working-directory: ${{ env.HOME }}
        shell: bash
        run: |
          curl -sSL https://github.com/nounfve-deploy/save_point_publish/releases/download/dev/save_point-${{ matrix.platform }}.zip -o save_point.zip
          unzip save_point.zip && chmod +x ./save_point
          mkdir -p ~/.local/bin/
          realpath ~/.local/bin/ >> $GITHUB_PATH
          ./save_point env install
          save_point --help
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v2
      - uses: actions/setup-node@v7
      - uses: actions/setup-python@v7
      - run: |
          npm i
          ./build.py
          ls -al working.temp/
        shell: bash
      - uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ matrix.platform }}
          path: |
            working.temp/*.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v7
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: flobro-inject-${{ github.sha }}
          tag_name: dev
          files: ./*/*.zip
          prerelease: true
          draft: false
          overwrite_files: true
