name: build

on:
  workflow_dispatch:
  push:
    tags:
      - dev
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - platform: windows-latest
          - platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: nounfve-deploy/save_point_publish/.github/use_sp@master
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v2
      - uses: actions/setup-node@v7
      - uses: actions/setup-python@v7
      - run: |
          npm i
          ./build.py
          ls -al working.temp/
        shell: bash
      - uses: actions/upload-artifact@v7
        with:
          name: wstream-${{ runner.os }}
          path: |
            working.temp/*.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.release.outputs.url }}
    steps:
      - uses: actions/download-artifact@v7
      - id: release
        uses: softprops/action-gh-release@v3
        with:
          name: wstream-${{ github.sha }}
          tag_name: dev
          files: ./*/*.zip
          prerelease: true
          draft: false
          overwrite_files: true
      - uses: nounfve-deploy/save_point_publish/.github/publish_notify@master
        with:
          release-url: ${{ steps.release.outputs.url }}
    